import type { Metadata } from "next";
import "./globals.css";
import Head from "./head";
import AuthProvider from "../context/AuthContext";
import TopNav from "../components/TopNav";
import Footer from "../components/Footer";
import TransactionsProvider from "../context/TransactionsContext";

export const metadata: Metadata = {
  title: "BudgetTer | Budget Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head />
      <AuthProvider>
        <TransactionsProvider>
          <body className="min-h-screen flex flex-col">
            <header className="flex flex-col gap-3 p-3 pb-0">
              <TopNav />
            </header>

            <div id="app" className="flex-grow">{children}</div>
            <div id="portal"></div>

            <footer>
              <Footer />
            </footer>
          </body>
        </TransactionsProvider>
      </AuthProvider>
    </html>
  );
}
