import type { Metadata } from "next";
import "./globals.css";
import Head from "./head";
import AuthProvider from "../../context/AuthContext";

export const metadata: Metadata = {
  title: "BudgetTer | Budget Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head />
      <AuthProvider>
        <body>
          <div id="app">{children}</div>
          <div id="portal"></div>
        </body>
      </AuthProvider>
    </html>
  );
}
